CREATE TABLE menus (
    id VARCHAR(26) NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;