### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "identifier": "admin-saja",
    "password": "admin-saja"
}

### Registrasi
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "tamu-saja",
    "email": "tamu-saja@gmail.com",
    "password": "tamu-saja"
}

### Logout
POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2MDcyNjAsImlhdCI6MTc1MDUyMDg2MCwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlk5SlMzU1RTMVlXVzk4Q1dXQ0haVlFIIiwidXNlcl9pZCI6IjAxSlk5REUzTVpYMEtISFE0S1M4NkowR0ROIn0.iRCjxdvymn5MuPfc4vncg8MJOBCYEenL_xUkzCvo19M
