### Ambil semua data
GET http://localhost:8080/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI4NDAsImlhdCI6MTc1MDU3NjQ0MCwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1M5MjZIOFRFS0RRTVIzRUNHU0g0IiwidXNlcl9pZCI6IjAxSllCN1FTV1RZOFpQUjJNQ0QzQ0Q5UzZKIn0.EqIWuJCdkkqf6mLaXvbIgsJ8Q_admgych6nok5frUeg

### Create
POST http://localhost:8080/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI4NDAsImlhdCI6MTc1MDU3NjQ0MCwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1M5MjZIOFRFS0RRTVIzRUNHU0g0IiwidXNlcl9pZCI6IjAxSllCN1FTV1RZOFpQUjJNQ0QzQ0Q5UzZKIn0.EqIWuJCdkkqf6mLaXvbIgsJ8Q_admgych6nok5frUeg
Content-Type: application/json

{
    "username": "editor-saja",
    "email": "editor-saja@gmail.com",
    "password": "editor-saja",
    "role_ids": ["01JYB7QSWTJTD9WPFH33NX396X"]
}
###

### Ambil data BY ID
GET http://localhost:8080/api/auth/users/01JXYV40T83BVAC9TYG3A7MJ7T
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI4NDAsImlhdCI6MTc1MDU3NjQ0MCwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1M5MjZIOFRFS0RRTVIzRUNHU0g0IiwidXNlcl9pZCI6IjAxSllCN1FTV1RZOFpQUjJNQ0QzQ0Q5UzZKIn0.EqIWuJCdkkqf6mLaXvbIgsJ8Q_admgych6nok5frUeg

### Update Data
PUT http://localhost:8080/api/auth/users/01JY12SQHBP2TJGG6CSG7ZANTY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI4NDAsImlhdCI6MTc1MDU3NjQ0MCwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1M5MjZIOFRFS0RRTVIzRUNHU0g0IiwidXNlcl9pZCI6IjAxSllCN1FTV1RZOFpQUjJNQ0QzQ0Q5UzZKIn0.EqIWuJCdkkqf6mLaXvbIgsJ8Q_admgych6nok5frUeg
Content-Type: application/json

{
    "username": "tamu-beserta-penulis",
    "email": "tamu-beserta-penulis@gmail.com",
    "role_ids": ["01JY9D574SD3C4KVT87J25DB2J"]
}
###

### Delete data
DELETE http://localhost:8080/api/auth/users/01JY0TS5HEQA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI4NDAsImlhdCI6MTc1MDU3NjQ0MCwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1M5MjZIOFRFS0RRTVIzRUNHU0g0IiwidXNlcl9pZCI6IjAxSllCN1FTV1RZOFpQUjJNQ0QzQ0Q5UzZKIn0.EqIWuJCdkkqf6mLaXvbIgsJ8Q_admgych6nok5frUeg