### Ambil semua data
GET http://localhost:8080/api/blog/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2ODExMzIsImlhdCI6MTc1MDU5NDczMiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCUzdGWjZFMEIwMFI3Sk40SFNLQjNNIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.q25U_-RFjMTZfuxJJO-Uu7OPdIPOuWI1HgDA3TogEW4

### Create
POST http://localhost:8080/api/blog/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2ODExMzIsImlhdCI6MTc1MDU5NDczMiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCUzdGWjZFMEIwMFI3Sk40SFNLQjNNIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.q25U_-RFjMTZfuxJJO-Uu7OPdIPOuWI1HgDA3TogEW4
Content-Type: application/json

{
    "description": "Kolom description wajib diisi",
    "name": "Kolom name wajib diisi"
}
###

### Ambil data BY ID
GET http://localhost:8080/api/blog/categories/01JXYV40T83BVAC9TYG3A7MJ7T
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2ODExMzIsImlhdCI6MTc1MDU5NDczMiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCUzdGWjZFMEIwMFI3Sk40SFNLQjNNIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.q25U_-RFjMTZfuxJJO-Uu7OPdIPOuWI1HgDA3TogEW4

### Update Data
PUT http://localhost:8080/api/blog/categories/01JY12SQHBP2TJGG6CSG7ZANTY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2ODExMzIsImlhdCI6MTc1MDU5NDczMiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCUzdGWjZFMEIwMFI3Sk40SFNLQjNNIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.q25U_-RFjMTZfuxJJO-Uu7OPdIPOuWI1HgDA3TogEW4
Content-Type: application/json

{
    "username": "tamu-beserta-penulis",
    "email": "tamu-beserta-penulis@gmail.com",
    "role_ids": ["01JXYT9YZ4Y728VWB60BNCAYD8", "p"]
}
###

### Delete data
DELETE http://localhost:8080/api/blog/categories/01JY0TS5HEQA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2ODExMzIsImlhdCI6MTc1MDU5NDczMiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCUzdGWjZFMEIwMFI3Sk40SFNLQjNNIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.q25U_-RFjMTZfuxJJO-Uu7OPdIPOuWI1HgDA3TogEW4