### Ambil semua data
GET http://localhost:8080/api/blog/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI5ODIsImlhdCI6MTc1MDU3NjU4Miwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1hNOTlSSFRRUUZUNVBESlcxSEdKIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.POZtQoxlnc1kM7-qTRbqHgc5n1EpDI8bQyHeS6BYpJM

### Create
POST http://localhost:8080/api/blog/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI5ODIsImlhdCI6MTc1MDU3NjU4Miwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1hNOTlSSFRRUUZUNVBESlcxSEdKIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.POZtQoxlnc1kM7-qTRbqHgc5n1EpDI8bQyHeS6BYpJM
Content-Type: application/json

{
    "name": "Panser Biru",
    "description": "Ini adalah salah satu definisi panser biru yang merakyat",
    "seo_description": "Panser biru yang merakyat"
}
###

### Ambil data BY ID
GET http://localhost:8080/api/blog/tags/01JYBJFQH78T2HHDBYBZZQ91GT
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI5ODIsImlhdCI6MTc1MDU3NjU4Miwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1hNOTlSSFRRUUZUNVBESlcxSEdKIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.POZtQoxlnc1kM7-qTRbqHgc5n1EpDI8bQyHeS6BYpJM

### Update Data
PUT http://localhost:8080/api/blog/tags/01JYBJFQH78T2HHDBYBZZQ91GT
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI5ODIsImlhdCI6MTc1MDU3NjU4Miwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1hNOTlSSFRRUUZUNVBESlcxSEdKIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.POZtQoxlnc1kM7-qTRbqHgc5n1EpDI8bQyHeS6BYpJM
Content-Type: application/json

{
    "name": "Panser Biru",
    "description": "Ini adalah salah satu definisi"
}
###

### Delete data
DELETE http://localhost:8080/api/blog/tags/01JYB7YSF5DMKT4ADTSB3BA6VB
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2NjI5ODIsImlhdCI6MTc1MDU3NjU4Miwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSllCN1hNOTlSSFRRUUZUNVBESlcxSEdKIiwidXNlcl9pZCI6IjAxSllCN1RTQVRRQ1k4RlNYS0hOWEI1UE5DIn0.POZtQoxlnc1kM7-qTRbqHgc5n1EpDI8bQyHeS6BYpJM