### Ambil semua data
GET http://localhost:8080/api/blog/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2MTkyMDcsImlhdCI6MTc1MDUzMjgwNywicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlk5WTVQWUY4TjQyRVdQTk5HMDJTRFRDIiwidXNlcl9pZCI6IjAxSlk5WTRIVjBHV0U4S1ZWN1dUTTZZQ1BSIn0.PJH637XW6t3zvaJLVDV1SMo75yh-ztPmaCML7OE4nT4

### Create
POST http://localhost:8080/api/blog/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2MTkyMDcsImlhdCI6MTc1MDUzMjgwNywicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlk5WTVQWUY4TjQyRVdQTk5HMDJTRFRDIiwidXNlcl9pZCI6IjAxSlk5WTRIVjBHV0U4S1ZWN1dUTTZZQ1BSIn0.PJH637XW6t3zvaJLVDV1SMo75yh-ztPmaCML7OE4nT4
Content-Type: application/json

{
    "name": "Gagah Berani Lho",
    "description": "Jang jawokan"
}
###

### Ambil data BY ID
GET http://localhost:8080/api/blog/tags/01JXYV40T83BVAC9TYG3A7MJ7T
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2MTkyMDcsImlhdCI6MTc1MDUzMjgwNywicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlk5WTVQWUY4TjQyRVdQTk5HMDJTRFRDIiwidXNlcl9pZCI6IjAxSlk5WTRIVjBHV0U4S1ZWN1dUTTZZQ1BSIn0.PJH637XW6t3zvaJLVDV1SMo75yh-ztPmaCML7OE4nT4

### Update Data
PUT http://localhost:8080/api/blog/tags/01JY12SQHBP2TJGG6CSG7ZANTY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2MTkyMDcsImlhdCI6MTc1MDUzMjgwNywicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlk5WTVQWUY4TjQyRVdQTk5HMDJTRFRDIiwidXNlcl9pZCI6IjAxSlk5WTRIVjBHV0U4S1ZWN1dUTTZZQ1BSIn0.PJH637XW6t3zvaJLVDV1SMo75yh-ztPmaCML7OE4nT4
Content-Type: application/json

{
    "username": "tamu-beserta-penulis",
    "email": "tamu-beserta-penulis@gmail.com",
    "role_ids": ["01JXYT9YZ4Y728VWB60BNCAYD8", "p"]
}
###

### Delete data
DELETE http://localhost:8080/api/blog/tags/01JY0TS5HEQA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA2MTkyMDcsImlhdCI6MTc1MDUzMjgwNywicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlk5WTVQWUY4TjQyRVdQTk5HMDJTRFRDIiwidXNlcl9pZCI6IjAxSlk5WTRIVjBHV0U4S1ZWN1dUTTZZQ1BSIn0.PJH637XW6t3zvaJLVDV1SMo75yh-ztPmaCML7OE4nT4