basePath: /
host: localhost:8080
info:
  contact: {}
  description: Blog system
  title: Blog - REST API Docs
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
